# Generated by Django 4.2.9 on 2024-07-05 20:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('description', models.TextField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('avg_rating', models.FloatField()),
                ('num_ratings', models.TextField()),
                ('url', models.TextField()),
                ('image', models.TextField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
